Update iac.yml

diff --git a/.github/workflows/iac.yml b/.github/workflows/iac.yml
--- a/.github/workflows/iac.yml
+++ b/.github/workflows/iac.yml
@@ -32,6 +32,17 @@ jobs:
           docker run \
             --env-file env.list \
             -v "$(pwd):/app/src" \
-            -v "$(pwd)/Policies:/app/Policies" \
             lacework/codesec:stable \
-            lacework iac scan --directory=. --custom-policy-dir=/app/Policies
+            lacework iac scan \
+              --directory=/app/src \
+              --output json > result.json
+
+          echo "Scan Results:"
+          cat result.json | jq .
+
+          if jq -e '.vulnerabilities[] | select(.severity == "Critical" or .severity == "High")' result.json > /dev/null; then
+            echo "Critical or High severity findings detected. Failing the job."
+            exit 1
+          else
+            echo "No Critical or High severity findings."
+          fi
