Update lacework-dockerfile-scan.yml

diff --git a/.github/workflows/lacework-dockerfile-scan.yml b/.github/workflows/lacework-dockerfile-scan.yml
--- a/.github/workflows/lacework-dockerfile-scan.yml
+++ b/.github/workflows/lacework-dockerfile-scan.yml
@@ -40,16 +40,23 @@ jobs:
           SAVE_RESULTS_IN_LACEWORK: true
           RESULTS_IN_GITHUB_SUMMARY: true
 
-      - name: Change formatting for PR
-        if: github.event_name == 'pull_request'
+      - name: Create Markdown results file
         run: |
           echo "# Lacework Inline Scanner Result" > pr-results.md
           echo "<pre>" >> pr-results.md
           cat results.stdout >> pr-results.md
           echo "</pre>" >> pr-results.md
 
-      - name: Comment PR with vulnerability scan results
+      - name: Comment on PR
         if: github.event_name == 'pull_request'
         uses: thollander/actions-comment-pull-request@v2
         with:
           filePath: pr-results.md
+
+      - name: Re-check scan result and fail if needed
+        run: |
+          if grep -q "Policy.*failed" results.stdout; then
+            echo "Lacework scan failed policy check. Failing job."
+            exit 1
+          fi
+
